//
// Generated file, do not edit! Created by opp_msgtool 6.0 from Message.msg.
//

#ifndef __MESSAGE_M_H
#define __MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Hello;
/**
 * Class generated from <tt>Message.msg:3</tt> by opp_msgtool.
 * <pre>
 * message Hello
 * {
 *     int Hop;
 *     int ID;
 *     int Seq;
 *     int clusterNum;
 * }
 * </pre>
 */
class Hello : public ::omnetpp::cMessage
{
  protected:
    int Hop = 0;
    int ID = 0;
    int Seq = 0;
    int clusterNum = 0;

  private:
    void copy(const Hello& other);

  protected:
    bool operator==(const Hello&) = delete;

  public:
    Hello(const char *name=nullptr, short kind=0);
    Hello(const Hello& other);
    virtual ~Hello();
    Hello& operator=(const Hello& other);
    virtual Hello *dup() const override {return new Hello(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHop() const;
    virtual void setHop(int Hop);

    virtual int getID() const;
    virtual void setID(int ID);

    virtual int getSeq() const;
    virtual void setSeq(int Seq);

    virtual int getClusterNum() const;
    virtual void setClusterNum(int clusterNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Hello& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Hello& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Hello *fromAnyPtr(any_ptr ptr) { return check_and_cast<Hello*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGE_M_H

